---
# handlers/main.yml: Handlers for RocketChat.Ansible
  - name: Reload the Nginx service
    service: name=nginx state=reloaded

  - name: Restart the MongoDB service
    service: name=mongod state=restarted

  - name: Upgrade Wekan
    include: upgrade.yml
    when: wekan_deploy_state.stat.exists
    tags:
      - upgrade

  - name: Update the Wekan service configuration
    shell: "{{ wekan_service_update_command }}"
    when: wekan_service_update_command is defined

  - name: Restart the Wekan service
    service: name=wekan state=restarted
